// ==============================================================================
// 📄 DATABASE: 200 QUESTIONS (6 POOLS)
// ==============================================================================

// 🟢 POOL A: Basic Grammar (30 Questions)
export const POOL_A = [
  { id: 1, q: "She __________ a student at the local college.", options: ["am", "is", "are", "be"], correct: "is" },
  { id: 2, q: "Where __________ they from?", options: ["am", "are", "is", "be"], correct: "are" },
  { id: 3, q: "I usually __________ breakfast at 7 o'clock.", options: ["eat", "eats", "eating", "am eat"], correct: "eat" },
  { id: 4, q: "My father __________ work on Sundays.", options: ["don't", "doesn't", "isn't", "not"], correct: "doesn't" },
  { id: 5, q: "__________ you like Italian pizza?", options: ["Does", "Do", "Are", "Is"], correct: "Do" },
  { id: 6, q: "There __________ two cats in the garden today.", options: ["is", "are", "be", "was"], correct: "are" },
  { id: 7, q: "She has got __________ orange in her bag.", options: ["a", "an", "some", "any"], correct: "an" },
  { id: 8, q: "My bag is __________ the chair in the kitchen.", options: ["in", "on", "at", "under"], correct: "on" },
  { id: 9, q: "What time __________ the train leave tomorrow?", options: ["do", "does", "is", "are"], correct: "does" },
  { id: 10, q: "I __________ my homework right now.", options: ["do", "does", "am doing", "doing"], correct: "am doing" },
  { id: 11, q: "Yesterday we __________ football after school.", options: ["play", "played", "plays", "playing"], correct: "played" },
  { id: 12, q: "We __________ to the park last weekend.", options: ["go", "goes", "went", "gone"], correct: "went" },
  { id: 13, q: "He __________ speak Spanish very well.", options: ["can", "cans", "is can", "can to"], correct: "can" },
  { id: 14, q: "This is my book. That one is __________.", options: ["my", "mine", "me", "I"], correct: "mine" },
  { id: 15, q: "How __________ sugar do you want in your tea?", options: ["many", "much", "any", "some"], correct: "much" },
  { id: 16, q: "They didn't __________ to the cinema last night.", options: ["go", "went", "going", "goes"], correct: "go" },
  { id: 17, q: "I'm __________ than my brother.", options: ["tall", "taller", "tallest", "more tall"], correct: "taller" },
  { id: 18, q: "Peter is the __________ player in the team.", options: ["stronger", "strongest", "most strong", "strong"], correct: "strongest" },
  { id: 19, q: "What __________ tomorrow evening?", options: ["will you do", "do you do", "are you going to do", "you do"], correct: "are you going to do" },
  { id: 20, q: "Does he have __________ sisters?", options: ["any", "some", "a", "an"], correct: "any" },
  { id: 21, q: "I sat __________ on the couch to watch the movie.", options: ["comfortable", "comfortably", "comfort", "comforting"], correct: "comfortably" },
  { id: 22, q: "__________ any water in the fridge?", options: ["Is there", "There is", "Is", "Are there"], correct: "Is there" },
  { id: 23, q: "That's __________ car. It's very expensive.", options: ["Anna's", "the car of Anna", "Anna car", "Anna is"], correct: "Anna's" },
  { id: 24, q: "I get up early __________ Sunday mornings.", options: ["in", "at", "on", "by"], correct: "on" },
  { id: 25, q: "When __________ they arrive at the station?", options: ["did", "do", "were", "was"], correct: "did" },
  { id: 26, q: "She __________ TV every evening after dinner.", options: ["watch", "watches", "watching", "watched"], correct: "watches" },
  { id: 27, q: "We have English lessons __________ Monday.", options: ["on", "at", "in", "for"], correct: "on" },
  { id: 28, q: "Can you __________ the window, please?", options: ["open", "opening", "opens", "opened"], correct: "open" },
  { id: 29, q: "They __________ from Uzbekistan.", options: ["is", "are", "am", "be"], correct: "are" },
  { id: 30, q: "I can't find my keys. I don't know where __________ are.", options: ["it", "them", "they", "their"], correct: "they" }
];

// 🟡 POOL B: Intermediate Grammar (40 Questions)
export const POOL_B = [
  { id: 31, q: "I __________ learning English for five years.", options: ["am", "was", "have been", "had been"], correct: "have been" },
  { id: 32, q: "If I __________ the lottery, I would buy a house.", options: ["win", "won", "had won", "would win"], correct: "won" },
  { id: 33, q: "She told me that she __________ the movie before.", options: ["saw", "has seen", "had seen", "sees"], correct: "had seen" },
  { id: 34, q: "That's the man __________ son is a famous actor.", options: ["who", "which", "whose", "that"], correct: "whose" },
  { id: 35, q: "You __________ have seen her—she's in Italy!", options: ["must", "can", "can't", "should"], correct: "can't" },
  { id: 36, q: "If you __________ ice, it melts.", options: ["heat", "heated", "will heat", "would heat"], correct: "heat" },
  { id: 37, q: "By the time he arrives, we __________ dinner.", options: ["finish", "will finish", "will have finished", "finished"], correct: "will have finished" },
  { id: 38, q: "I wish I __________ more time yesterday.", options: ["have", "had", "had had", "would have"], correct: "had had" },
  { id: 39, q: "The results __________ tomorrow morning.", options: ["are announced", "will be announced", "announced", "be announced"], correct: "will be announced" },
  { id: 40, q: "He denied __________ on the final exam.", options: ["to cheat", "cheating", "cheat", "to cheating"], correct: "cheating" },
  { id: 41, q: "I look forward __________ you next week.", options: ["to meet", "meeting", "to meeting", "meet"], correct: "to meeting" },
  { id: 42, q: "Despite __________ rain, we went for a walk.", options: ["of the", "the", "it was", "although"], correct: "the" },
  { id: 43, q: "If he __________ earlier, he wouldn't have missed it.", options: ["left", "leaves", "had left", "would leave"], correct: "had left" },
  { id: 44, q: "Sam hopes __________ an astronaut one day.", options: ["becoming", "to become", "become", "to becoming"], correct: "to become" },
  { id: 45, q: "I __________ to reach her on the phone all day.", options: ["tried", "have been trying", "have tried", "try"], correct: "have been trying" },
  { id: 46, q: "By next month, I __________ all my exams.", options: ["finish", "will finish", "will have finished", "am finishing"], correct: "will have finished" },
  { id: 47, q: "I'm very happy __________ in India last year.", options: ["to live", "to have lived", "living", "to be lived"], correct: "to have lived" },
  { id: 48, q: "I wish I __________ those words to him then.", options: ["not say", "hadn't said", "didn't say", "haven't said"], correct: "hadn't said" },
  { id: 49, q: "The woman is believed __________ by the group.", options: ["to be abducted", "to have been abducted", "abducting", "to abduct"], correct: "to have been abducted" },
  { id: 50, q: "In no way __________ he be forced to join.", options: ["was", "he was", "should", "did"], correct: "should" },
  { id: 51, q: "It __________ the best idea to pay by credit card.", options: ["may not have been", "may not be", "must not be", "might not be"], correct: "may not have been" },
  { id: 52, q: "They __________ to sleep in the basement.", options: ["were made", "made", "were made to", "were making"], correct: "were made to" },
  { id: 53, q: "If success __________, we must work hard.", options: ["is to be achieved", "achieved", "is achieved", "achieves"], correct: "is to be achieved" },
  { id: 54, q: "I __________ my homework when the phone rang.", options: ["did", "was doing", "have done", "do"], correct: "was doing" },
  { id: 55, q: "I __________ have short hair, but now it's long.", options: ["used to", "before", "use to", "didn't"], correct: "used to" },
  { id: 56, q: "Take an umbrella __________ it rains later.", options: ["if", "when", "in case", "so"], correct: "in case" },
  { id: 57, q: "She suggested __________ to the park.", options: ["to go", "going", "that we go", "both B and C"], correct: "both B and C" },
  { id: 58, q: "Neither of the students __________ finished the test.", options: ["have", "has", "are", "were"], correct: "has" },
  { id: 59, q: "The report will be submitted, __________ revisions are needed.", options: ["because", "if", "despite", "unless"], correct: "unless" },
  { id: 60, q: "He drives quite __________, but his brother is fast.", options: ["slow", "slowly", "slowy", "slowness"], correct: "slowly" },
  { id: 61, q: "She is really good __________ solving problems.", options: ["at", "in", "on", "of"], correct: "at" },
  { id: 62, q: "Let's go to the cinema, __________ we?", options: ["will", "shall", "do", "are"], correct: "shall" },
  { id: 63, q: "I haven't seen Mark __________ three weeks.", options: ["since", "for", "during", "from"], correct: "for" },
  { id: 64, q: "The book __________ was published last year is great.", options: ["who", "which", "whom", "where"], correct: "which" },
  { id: 65, q: "He __________ go to the meeting if he has time.", options: ["would", "will", "can", "must"], correct: "will" },
  { id: 66, q: "I __________ finished my work by 6 PM.", options: ["will", "will have", "have", "will be"], correct: "will have" },
  { id: 67, q: "She apologized __________ being late.", options: ["for", "to", "of", "at"], correct: "for" },
  { id: 68, q: "I'd rather you __________ tell him the truth.", options: ["don't", "didn't", "won't", "not"], correct: "didn't" },
  { id: 69, q: "It's time we __________ home.", options: ["go", "went", "are going", "will go"], correct: "went" },
  { id: 70, q: "She managed __________ the project on time.", options: ["finish", "to finish", "finishing", "finished"], correct: "to finish" }
];

// 🔴 POOL C: Expert Grammar (30 Questions)
export const POOL_C = [
  { id: 71, q: "Not until now __________ that man is destroying his environment.", options: ["it has become", "it becomes", "does it become", "has it become"], correct: "has it become" },
  { id: 72, q: "No sooner __________ the match than flames shot across the floor.", options: ["did he drop", "he dropped", "he had dropped", "had he dropped"], correct: "had he dropped" },
  { id: 73, q: "Hardly __________ the harbour when a storm broke out.", options: ["had we left", "we had left", "we left", "we did leave"], correct: "had we left" },
  { id: 74, q: "Not for one moment __________ my friend's innocence.", options: ["I doubted", "I did doubt", "did I doubt", "I doubt"], correct: "did I doubt" },
  { id: 75, q: "__________ I really need is a long vacation.", options: ["That", "What", "Which", "It"], correct: "What" },
  { id: 76, q: "Under no circumstances __________ children be allowed to drive.", options: ["no sooner", "should", "are", "will"], correct: "should" },
  { id: 77, q: "Only when Jane has arrived __________ start the party.", options: ["we can", "can we", "did we", "we do"], correct: "can we" },
  { id: 78, q: "It was Nick __________ turned up late on Monday.", options: ["which", "who", "whom", "whose"], correct: "who" },
  { id: 79, q: "__________ expensive it is, I am going to buy it.", options: ["However", "Although", "Nevertheless", "But"], correct: "However" },
  { id: 80, q: "If he __________ the 8.10 train, he would be here now.", options: ["doesn't miss", "wouldn't miss", "hadn't missed", "wasn't missing"], correct: "hadn't missed" },
  { id: 81, q: "Sarah and John are late. They __________ lost.", options: ["must get", "must have got", "must to get", "must have be"], correct: "must have got" },
  { id: 82, q: "Only after she had left __________ what she meant.", options: ["I understood", "did I understand", "I had understood", "do I understand"], correct: "did I understand" },
  { id: 83, q: "I can't believe it! Do you mean Barry __________ money all this time?", options: ["was stolen", "has been stealing", "stole", "is stealing"], correct: "has been stealing" },
  { id: 84, q: "By the end of this year, he __________ here for fifty years.", options: ["will live", "will have been living", "has been living", "will be living"], correct: "will have been living" },
  { id: 85, q: "__________ you the job, would you accept?", options: ["Did they offer", "Were they to offer", "If they had offered", "Were they offered"], correct: "Were they to offer" },
  { id: 86, q: "It is essential that she __________ at the meeting tomorrow.", options: ["be", "is", "was", "will be"], correct: "be" },
  { id: 87, q: "If I __________ you, I would call her tonight.", options: ["was", "were", "am", "be"], correct: "were" },
  { id: 88, q: "The owner asks that the last person __________ off the lights.", options: ["turns", "turn", "turned", "is turning"], correct: "turn" },
  { id: 89, q: "I wish that my favourite café __________ open on Sundays.", options: ["was", "were", "is", "be"], correct: "were" },
  { id: 90, q: "If need __________, I will do it myself.", options: ["is", "be", "was", "were"], correct: "be" },
  { id: 91, q: "__________ much work he takes on, he always has difficulty.", options: ["How", "However", "No matter", "Although"], correct: "However" },
  { id: 92, q: "The more he does for her, __________ dissatisfied she seems.", options: ["she seems", "the more", "more", "the most"], correct: "the more" },
  { id: 93, q: "You __________ a hand with moving the furniture!", options: ["would have given", "might have given", "should give", "had to give"], correct: "might have given" },
  { id: 94, q: "__________ for her support, he would have given up.", options: ["Had it not been", "Unless it was", "If she hadn't been", "If it were"], correct: "Had it not been" },
  { id: 95, q: "I was __________ you liked Indian food.", options: ["off the idea", "under the impression", "thinking", "in response to"], correct: "under the impression" },
  { id: 96, q: "She seems fun, but it would be a mistake to __________ her.", options: ["underrate", "despise", "depreciate", "devalue"], correct: "underrate" },
  { id: 97, q: "Your name __________ in the course of our conversation.", options: ["brought", "came up", "got", "took"], correct: "came up" },
  { id: 98, q: "She __________ a rage when she saw the mess.", options: ["flew into", "went off", "blew up", "came into"], correct: "flew into" },
  { id: 99, q: "We only see her once in a __________ moon.", options: ["red", "blue", "full", "new"], correct: "blue" },
  { id: 100, q: "John is on the __________ of a nervous breakdown.", options: ["closed to", "on edge", "nearby", "verge"], correct: "verge" }
];

// 🔵 POOL D: Basic Vocabulary (30 Questions)
export const POOL_D = [
  { id: 101, q: "I love all fruit, but I like __________ strawberries.", options: ["mostly", "especially", "specially"], correct: "especially" },
  { id: 102, q: "What time do you go to __________ every day?", options: ["office", "job", "work"], correct: "work" },
  { id: 103, q: "My father's brother is my __________.", options: ["aunt", "uncle", "cousin"], correct: "uncle" },
  { id: 104, q: "I need to buy a __________ to carry my money.", options: ["garage", "bike", "wallet"], correct: "wallet" },
  { id: 105, q: "The sky is __________ on a sunny day.", options: ["blue", "green", "yellow"], correct: "blue" },
  { id: 106, q: "I'm a __________. I study at the university.", options: ["professor", "student", "teacher"], correct: "student" },
  { id: 107, q: "Can you __________ the door? It's cold outside.", options: ["open", "close", "jump"], correct: "close" },
  { id: 108, q: "Breakfast, lunch, and dinner are __________.", options: ["food", "meals", "drinks"], correct: "meals" },
  { id: 109, q: "'Happy' is the __________ of 'sad'.", options: ["opposite", "opposed", "same"], correct: "opposite" },
  { id: 110, q: "I use a __________ to write on paper.", options: ["book", "kite", "pen"], correct: "pen" },
  { id: 111, q: "Who is the person flying the plane? The ________.", options: ["driver", "pilot", "flyer"], correct: "pilot" },
  { id: 112, q: "Jack __________ his motorcycle to work every day.", options: ["drives", "flies", "rides"], correct: "rides" },
  { id: 113, q: "The person who helps you in a shop is a ________.", options: ["customer", "sales assistant", "cleaner"], correct: "sales assistant" },
  { id: 114, q: "It was __________ outside, so we could not see well.", options: ["noisy", "foggy", "regular"], correct: "foggy" },
  { id: 115, q: "I need to __________ my homework before dinner.", options: ["make", "have", "do"], correct: "do" },
  { id: 116, q: "If you don't __________ , we'll be late for the bus.", options: ["worry", "hurry", "visit"], correct: "hurry" },
  { id: 117, q: "My hair isn't straight; it is slightly __________. ", options: ["curl", "bend", "wavy"], correct: "wavy" },
  { id: 118, q: "We use the __________ to go to the 10th floor.", options: ["closet", "elevator", "ceiling"], correct: "elevator" },
  { id: 119, q: "She is an __________ child; she has no brothers.", options: ["alone", "only", "single"], correct: "only" },
  { id: 120, q: "A __________ is a dairy product.", options: ["cheese", "meat", "rice"], correct: "cheese" },
  { id: 121, q: "I __________ my passport. Have you seen it?", options: ["found", "lost", "offered"], correct: "lost" },
  { id: 122, q: "Please __________ your shoes before you enter.", options: ["put on", "take off", "get up"], correct: "take off" },
  { id: 123, q: "I like __________ at the gym three times a week.", options: ["working out", "taking out", "going out"], correct: "working out" },
  { id: 124, q: "The weather is __________ today. Let's stay inside.", options: ["simple", "awful", "close"], correct: "awful" },
  { id: 125, q: "Joe's mum's brothers are Joe's __________.", options: ["aunts", "uncles", "nephews"], correct: "uncles" },
  { id: 126, q: "I'm going to the __________ to borrow some books.", options: ["library", "shop", "factory"], correct: "library" },
  { id: 127, q: "Can you __________ the window? It’s very hot.", options: ["open", "turn", "move"], correct: "open" },
  { id: 128, q: "My sister is a __________; she works in a hospital.", options: ["nurse", "pilot", "driver"], correct: "nurse" },
  { id: 129, q: "He bought a leather __________ for his new jeans.", options: ["boot", "belt", "hat"], correct: "belt" },
  { id: 130, q: "She is very __________; she cries at every movie.", options: ["sensitive", "arrogant", "brave"], correct: "sensitive" }
];

// 🟣 POOL E: Intermediate Vocabulary (40 Questions)
export const POOL_E = [
  { id: 131, q: "It's a ________ that Peter can't come to the party.", options: ["pity", "wish", "type"], correct: "pity" },
  { id: 132, q: "The __________ from London to New York is 6 hours.", options: ["flight", "tour", "voyage"], correct: "flight" },
  { id: 133, q: "I want to __________ my goal of becoming a doctor.", options: ["invent", "achieve", "acquire"], correct: "achieve" },
  { id: 134, q: "A person who repairs things made of iron is a _____.", options: ["priest", "blacksmith", "shepherd"], correct: "blacksmith" },
  { id: 135, q: "Our __________ of the pyramids was fantastic.", options: ["route", "tour", "field trip"], correct: "tour" },
  { id: 136, q: "Sonia __________ her job to find a new challenge.", options: ["resigned", "applied", "retired"], correct: "resigned" },
  { id: 137, q: "If you are __________ a shop, you are the leader.", options: ["responsible", "in charge of", "retired"], correct: "in charge of" },
  { id: 138, q: "He is very __________; he always gives gifts.", options: ["modest", "generous", "arrogant"], correct: "generous" },
  { id: 139, q: "The act of traveling with a bag on your back is ____.", options: ["cruise", "backpacking", "staycation"], correct: "backpacking" },
  { id: 140, q: "I don't __________ going out tonight; I'm tired.", options: ["feel like", "want", "like"], correct: "feel like" },
  { id: 141, q: "A __________ is a journey made for religious reasons.", options: ["safari", "pilgrimage", "road trip"], correct: "pilgrimage" },
  { id: 142, q: "We had to __________ our holiday because of rain.", options: ["call off", "put on", "get along"], correct: "call off" },
  { id: 143, q: "The path you take to reach a place is the ________.", options: ["destination", "route", "voyage"], correct: "route" },
  { id: 144, q: "A __________ takes care of a building or a place.", options: ["shepherd", "caretaker", "blacksmith"], correct: "caretaker" },
  { id: 145, q: "To __________ someone means to hurt their feelings.", options: ["offend", "deceive", "sustain"], correct: "offend" },
  { id: 146, q: "I've __________ my blood pressure at the doctor's.", options: ["had", "tested", "made"], correct: "tested" },
  { id: 147, q: "My brother is very __________; he wants to be CEO.", options: ["amusing", "ambitious", "considerate"], correct: "ambitious" },
  { id: 148, q: "The elevators aren't __________; they often break.", options: ["reliable", "honest", "regular"], correct: "reliable" },
  { id: 149, q: "'Hatred' means __________.", options: ["intense dislike", "modest", "violating"], correct: "intense dislike" },
  { id: 150, q: "We __________ to work, but now we take the train.", options: ["used to drive", "used to drove", "drive"], correct: "used to drive" },
  { id: 151, q: "Our neighbor is a __________ smoker (2 packs a day).", options: ["hard", "strong", "heavy"], correct: "heavy" },
  { id: 152, q: "It was __________ coincidence that I saw him there.", options: ["clear", "pure", "great"], correct: "pure" },
  { id: 153, q: "The cruise was great, and our __________ was comfy.", options: ["cabin", "terminal", "fare"], correct: "cabin" },
  { id: 154, q: "I'm an honest and __________-abiding citizen.", options: ["lawful", "law", "legal"], correct: "law" },
  { id: 155, q: "I'm really __________ to my upcoming beach holiday.", options: ["looking forward", "getting on", "putting off"], correct: "looking forward" },
  { id: 156, q: "He __________ his mother with his artistic talent.", options: ["takes after", "looks after", "turns up"], correct: "takes after" },
  { id: 157, q: "I can't believe the cruise is costing a __________!", options: ["fortune", "earth", "money"], correct: "fortune" },
  { id: 158, q: "Emily is so __________; she thinks she's better.", options: ["arrogant", "sensitive", "loving"], correct: "arrogant" },
  { id: 159, q: "I'm afraid Joe is on the __________ of a breakdown.", options: ["verge", "edge", "blink"], correct: "verge" },
  { id: 160, q: "The meeting was __________ because of the rain.", options: ["called off", "fell out", "turn up"], correct: "called off" },
  { id: 161, q: "She has had a lot of experience but no __________.", options: ["qualifications", "shifts", "works"], correct: "qualifications" },
  { id: 162, q: "I called him by the wrong name __________.", options: ["by heart", "by chance", "by mistake"], correct: "by mistake" },
  { id: 163, q: "The siren of the ambulance was __________.", options: ["wailing", "splashing", "crashing"], correct: "wailing" },
  { id: 164, q: "Don't forget to leave a __________ for the waiter.", options: ["donation", "tip", "allowance"], correct: "tip" },
  { id: 165, q: "The two countries didn't reach an __________.", options: ["agreement", "agree", "agreeing"], correct: "agreement" },
  { id: 166, q: "I need to go to the store; we've __________ milk.", options: ["run out of", "put up with", "figure out"], correct: "run out of" },
  { id: 167, q: "Neil __________ an article about an old friend.", options: ["came across", "came into", "came up"], correct: "came across" },
  { id: 168, q: "He tried to __________ his friend's mistakes.", options: ["turn a blind eye to", "look up to", "get on"], correct: "turn a blind eye to" },
  { id: 169, q: "They __________ over a silly argument.", options: ["fell out", "gets along", "turn up"], correct: "fell out" },
  { id: 170, q: "We need to __________ the candidates for the job.", options: ["sift through", "see through", "take away"], correct: "sift through" }
];

// 🟠 POOL F: Advanced Idioms & Vocab (30 Questions)
export const POOL_F = [
  { id: 171, q: "Smartphones are ________; you see them everywhere.", options: ["ubiquitous", "rare", "outdated"], correct: "ubiquitous" },
  { id: 172, q: "The manager's __________ attention to detail was key.", options: ["meticulous", "careless", "disorganized"], correct: "meticulous" },
  { id: 173, q: "To __________ a situation means to reduce its pain.", options: ["mitigate", "exaggerate", "validate"], correct: "mitigate" },
  { id: 174, q: "She was feeling __________, so she stayed home.", options: ["under the weather", "on cloud nine", "thrilled"], correct: "under the weather" },
  { id: 175, q: "The news about the fire spread like __________.", options: ["wildfire", "air", "water"], correct: "wildfire" },
  { id: 176, q: "He is very __________; he sees things others miss.", options: ["astute", "ignorant", "aggressive"], correct: "astute" },
  { id: 177, q: "She has a __________ for avant-garde art.", options: ["penchant", "hatred", "ignorance"], correct: "penchant" },
  { id: 178, q: "The professor's lecture was so __________ I slept.", options: ["tedious", "informative", "succinct"], correct: "tedious" },
  { id: 179, q: "The company __________ a new marketing campaign.", options: ["launched", "injected", "wrapped"], correct: "launched" },
  { id: 180, q: "He was __________ with measles after several tests.", options: ["diagnosed", "treated", "refused"], correct: "diagnosed" },
  { id: 181, q: "'Succinct' means __________.", options: ["brief and clear", "long", "boring"], correct: "brief and clear" },
  { id: 182, q: "The scientist made a __________ argument for energy.", options: ["plausible", "illogical", "weak"], correct: "plausible" },
  { id: 183, q: "I don't want to __________ my intelligence.", options: ["underrate", "despise", "devalue"], correct: "underrate" },
  { id: 184, q: "She is always jumping on the __________ (following trends).", options: ["bandwagon", "cloud", "wall"], correct: "bandwagon" },
  { id: 185, q: "The result was the __________ of years of work.", options: ["culmination", "beginning", "failure"], correct: "culmination" },
  { id: 186, q: "He's very __________, paying great attention to rules.", options: ["fastidious", "gregarious", "lucid"], correct: "fastidious" },
  { id: 187, q: "Matters finally __________ at the office and he was fired.", options: ["came to a head", "hit the roof", "tore off"], correct: "came to a head" },
  { id: 188, q: "He promised to stick by her through __________ (always).", options: ["thick and thin", "spick and span", "odds and ends"], correct: "thick and thin" },
  { id: 189, q: "The Olympic committee does not __________ drug use.", options: ["condone", "expunge", "insulate"], correct: "condone" },
  { id: 190, q: "His interest in the sport began to __________ (decrease).", options: ["wane", "bloat", "instil"], correct: "wane" },
  { id: 191, q: "The previous tenants were __________ for not paying.", options: ["evicted", "sentenced", "assessed"], correct: "evicted" },
  { id: 192, q: "She was really __________ a cigarette after the flight.", options: ["craving", "plunging", "preserving"], correct: "craving" },
  { id: 193, q: "He finally decided to __________ and buy a house.", options: ["take the plunge", "jump the gun", "face music"], correct: "take the plunge" },
  { id: 194, q: "After hearing the news, he was on __________ nine.", options: ["cloud", "moon", "star"], correct: "cloud" },
  { id: 195, q: "It's time to __________ (accept consequences).", options: ["face the music", "break the ice", "spill beans"], correct: "face the music" },
  { id: 196, q: "The car is __________ to the other makes in the garage.", options: ["superior", "better", "above"], correct: "superior" },
  { id: 197, q: "I heard a __________ outside; men were arguing loudly.", options: ["commotion", "ritual", "burial"], correct: "commotion" },
  { id: 198, q: "The pizza place tried to __________ by using cheap cheese.", options: ["cut corners", "call shots", "talk shop"], correct: "cut corners" },
  { id: 199, q: "His trip happened to __________ with the holiday. ", options: ["coincide", "mingle", "ponder"], correct: "coincide" },
  { id: 200, q: "As this is a reproduction, it is practically __________.", options: ["worthless", "priceless", "invaluable"], correct: "worthless" }
];